[project]
name = "auth-server"
version = "1.0.0"
description = "Authorization Server"
authors = [{name = "Your Name"}]

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"
